server:
  port: 8080
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: GreenPath
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/Test
    username: Alfred
    driver-class-name: org.postgresql.Driver
    password: alfybooze
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000

  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # Thymeleaf Configuration
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true

  # Session Configuration
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always 
      table-name: SPRING_SESSION
      cleanup-cron: "0 * * * * *"
    timeout: 30m
    cookie:
      name: JSESSIONID
      max-age: 30m
      http-only: true
      secure: false
      same-site: lax

# Application-specific configuration
app:
  websocket:
    endpoint: /ws
    destination-prefix: /app
    broker-prefix: /topic
  security:
    remember-me:
      key: ${REMEMBER_ME_KEY} 
      token-validity-seconds: 1209600 
    session:
      maximum-sessions: 1
      prevent-login-if-maximum-exceeded: false
      expired-url: /login?expired
      invalid-session-url: /login?invalid
  upload:
    max-file-size: 10MB
    max-request-size: 10MB